version: "3.9"
services:
  aworker:
    build: .
    volumes:
      - .:/code
      - alogvolume01:/var/log
    links:
      - aredis
    ports:
      - "5000:5000"  
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_ID: ${SESSION_ID}
      REMOVEBG_KEY: ${REMOVEBG_KEY}
      PREFIX: ${PREFIX}
  aredis:
    image: aredis
volumes:
  alogvolume01: {}
