version: "3.9"
services:
  dyworker:
    build: .
    volumes:
      - .:/code
      - 1alogvolume01:/var/log
    links:
      - 1aredis
    ports:
      - "8000:8000"  
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_ID: ${SESSION_ID}
      REMOVEBG_KEY: ${REMOVEBG_KEY}
      PREFIX: ${PREFIX}
  1aredis:
    image: 1aredis
volumes:
  1alogvolume01: {}
